<<<<<<< HEAD
[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.40.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
=======
[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.48"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
>>>>>>> 6bcd182537d190f90e16ab44bbe4364c806333a1
